var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
function range(a,c,b){"undefined"==typeof c&&(c=a,a=0);"undefined"==typeof b&&(b=1);if(0<b&&a>=c||0>b&&a<=c)return[];for(var d=[];0<b?a<c:a>c;a+=b)d.push(a);return d}var counter_Index,partsNew,patterns,counter_total,k,j,pattern,pattern_start_pos,sentences,test,newData=[],urlData=[],counter_Array=[];
function split_into_chunks(a,c,b,d){c=void 0===c?5:c;b=void 0===b?0:b;d=[];partsNew=[];a=a.split(" ");for(var m=0,h=Math.ceil(a.length/c);m<h;m+=1){var f=m*c;var n=a.slice(f,f+c);f=!0;var g=n.join(" ");n.length<b&&(f=!1);f&&d.push(g)}return d}function len(a){return a.length}
function replaceDomainExte(a){return a.replace(/(^\w+:|^)\/\//,"").replace(RegExp(".?(.gov|org|co|com|in|info|net|uk|af|am|ar|au|as|az|be|bg|bn|bo|bs|ca|cs|cy|da|de|dv|el|en|es|et|eu|fa|fi|fo|fr|gd|gl|gn|gu|he|hi|hr|hu|hy|id|is|it|jp|ka|kk|km|kn|ko|ks|la|lo|lt|lv|mi|mk|ml|mn|mr|ms|mt|my|nb|ne|nl|or|pa|pl|pt|rm|ro|ru|sa|sb|sd|si|sk|sl|so|sq|sr|sv|sw|ta|te|tg|th|tk|tn|tr|ts|tt|uk|ur|uz|vi|xh|yi|zh|zu)+$"),"")}
function _$xyhkmtydfghertry(a,c){var b,d,m=!0,h,f,n;counter_Index=counter_total=b=0;if(50>parseInt(a.replace(/\s+/g," ").length))return showModel("Empty words/characters","<p>Please type at least hundred characters to begin</p>"),!1;var g=userResponse();if(0==g)return!1;var u=g.googleResponse,v=g.serverResponse;g=g.timeleft;if(0==u&&0==v)return showModel("Authentication error","Please make sure to check the captcha before proceeding"),!1;if(1==u&&0==v)return showModel("Authentication error","You have exceeded your free daily usage. Come back in the next "+
g+" minutes"),!1;if(0==u&&1==v)return showModel("Authentication error","Please check the captcha form before continuing"),!1;a=a.replace(/\s+/g," ").trim();a=a.replace(/[,]+/g,",");a=a.replace(/[.]+/g,".");a=a.replace(/[:]+/g,":");a=a.replace(/[?]+/g,"?");var l=split_into_chunks(a,50);$("#hideIt").show();for(i in l)30>l[i].split(" ").length||($([l]).each(function(){var x=l[i];$.ajax({url:"checkPlager.php",type:"POST",data:{number:x},success:function(e){try{jQuery.parseJSON(e)}catch(t){t&&(m=!1)}if(!0!==
m)return showModel("Something went wrong","Something went wrong. Please wait for a while and try again"),$("#hideIt").hide(),!1;resp=jQuery.parseJSON(e);dataIndex=l.indexOf(x);sentences=split_into_chunks(l[dataIndex],5);e=$jscomp.makeIterator(sentences);for(var w=e.next();!w.done;w=e.next())pattern=w.value,pattern=pattern.trim(" "),0<len(pattern)&&(counter_total++,$.each(resp.items,function(t,p){pattern_start_pos=0;for(d=!1;pattern_start_pos+pattern.length<=len(p.snippet);){var q=pattern_start_pos+
pattern.length,r=0+pattern.length;for(t=0;r>t;)if(pattern[r-1].toLowerCase()==p.snippet[q-1].toLowerCase()){if(--q,--r,q==pattern_start_pos){d=!0;break}}else{pattern_start_pos=-1==(new Slice(null,r-1)).get(pattern).lastIndexOf(p.snippet[q-1])?pattern_start_pos+pattern.length:pattern_start_pos+pattern.length-(new Slice(null,r-1)).get(pattern).lastIndexOf(p.snippet[q-1])-1;break}if(1==d){h=p.link;valueLink=h.trim();f="<li style='color:white;background-color:black'>"+h+"</li><br>";n=document.getElementById("urlcontents");
1==urlData.includes(h)?urlData:urlData.push(h)?n.insertAdjacentHTML("beforeend",f):urlData;1==newData.includes(pattern)?newData:newData.push(pattern);b=newData.length;for(var y in l)dataIndex==y&&(counter_Array[y]=counter_Index++);break}}}));e=split_into_chunks(c,200)[0];for(var z in newData)e=e.replace(newData[z],"<span id='data' style='color:black;background-color:orange'>"+newData[z]+" </span>");$("#contents").html(e);0<100*b/counter_total&&41>100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+
(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em></strong>and <strong style="color:green">'+(100-100*b/counter_total).toFixed(2)+"% original. It needs optimal improvement</strong></span><br /><br />"):40<100*b/counter_total&&100>100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em> </strong>and <strong style="color:green">'+(100-100*b/counter_total).toFixed(2)+
'% original. </strong><strong style="color:red">It needs critical improvement</strong></span><br />'):100==100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em> </strong>and<strong style="color:red">it needs critical improvement</strong></span><br />'):$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:green">100% original</strong></span><br />');
$("#urlSource").show()}})}),$(document).ajaxStop(function(){$("#hideIt").hide()}))};
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
function range(a,c,b){"undefined"==typeof c&&(c=a,a=0);"undefined"==typeof b&&(b=1);if(0<b&&a>=c||0>b&&a<=c)return[];for(var d=[];0<b?a<c:a>c;a+=b)d.push(a);return d}var counter_Index,partsNew,patterns,counter_total,k,j,pattern,pattern_start_pos,sentences,test,newData=[],urlData=[],counter_Array=[];
function split_into_chunks(a,c,b,d){c=void 0===c?5:c;b=void 0===b?0:b;d=[];partsNew=[];a=a.split(" ");for(var m=0,h=Math.ceil(a.length/c);m<h;m+=1){var f=m*c;var n=a.slice(f,f+c);f=!0;var g=n.join(" ");n.length<b&&(f=!1);f&&d.push(g)}return d}function len(a){return a.length}
function replaceDomainExte(a){return a.replace(/(^\w+:|^)\/\//,"").replace(RegExp(".?(.gov|org|co|com|in|info|net|uk|af|am|ar|au|as|az|be|bg|bn|bo|bs|ca|cs|cy|da|de|dv|el|en|es|et|eu|fa|fi|fo|fr|gd|gl|gn|gu|he|hi|hr|hu|hy|id|is|it|jp|ka|kk|km|kn|ko|ks|la|lo|lt|lv|mi|mk|ml|mn|mr|ms|mt|my|nb|ne|nl|or|pa|pl|pt|rm|ro|ru|sa|sb|sd|si|sk|sl|so|sq|sr|sv|sw|ta|te|tg|th|tk|tn|tr|ts|tt|uk|ur|uz|vi|xh|yi|zh|zu)+$"),"")}
function _$xyhkmtydfghertry(a,c){var b,d,m=!0,h,f,n;counter_Index=counter_total=b=0;if(50>parseInt(a.replace(/\s+/g," ").length))return showModel("Empty words/characters","<p>Please type at least hundred characters to begin</p>"),!1;var g=userResponse();if(0==g)return!1;var u=g.googleResponse,v=g.serverResponse;g=g.timeleft;if(0==u&&0==v)return showModel("Authentication error","Please make sure to check the captcha before proceeding"),!1;if(1==u&&0==v)return showModel("Authentication error","You have exceeded your free daily usage. Come back in the next "+
g+" minutes"),!1;if(0==u&&1==v)return showModel("Authentication error","Please check the captcha form before continuing"),!1;a=a.replace(/\s+/g," ").trim();a=a.replace(/[,]+/g,",");a=a.replace(/[.]+/g,".");a=a.replace(/[:]+/g,":");a=a.replace(/[?]+/g,"?");var l=split_into_chunks(a,50);$("#hideIt").show();for(i in l)30>l[i].split(" ").length||($([l]).each(function(){var x=l[i];$.ajax({url:"checkPlager.php",type:"POST",data:{number:x},success:function(e){try{jQuery.parseJSON(e)}catch(t){t&&(m=!1)}if(!0!==
m)return showModel("Something went wrong","Something went wrong. Please wait for a while and try again"),$("#hideIt").hide(),!1;resp=jQuery.parseJSON(e);dataIndex=l.indexOf(x);sentences=split_into_chunks(l[dataIndex],5);e=$jscomp.makeIterator(sentences);for(var w=e.next();!w.done;w=e.next())pattern=w.value,pattern=pattern.trim(" "),0<len(pattern)&&(counter_total++,$.each(resp.items,function(t,p){pattern_start_pos=0;for(d=!1;pattern_start_pos+pattern.length<=len(p.snippet);){var q=pattern_start_pos+
pattern.length,r=0+pattern.length;for(t=0;r>t;)if(pattern[r-1].toLowerCase()==p.snippet[q-1].toLowerCase()){if(--q,--r,q==pattern_start_pos){d=!0;break}}else{pattern_start_pos=-1==(new Slice(null,r-1)).get(pattern).lastIndexOf(p.snippet[q-1])?pattern_start_pos+pattern.length:pattern_start_pos+pattern.length-(new Slice(null,r-1)).get(pattern).lastIndexOf(p.snippet[q-1])-1;break}if(1==d){h=p.link;valueLink=h.trim();f="<li style='color:white;background-color:black'>"+h+"</li><br>";n=document.getElementById("urlcontents");
1==urlData.includes(h)?urlData:urlData.push(h)?n.insertAdjacentHTML("beforeend",f):urlData;1==newData.includes(pattern)?newData:newData.push(pattern);b=newData.length;for(var y in l)dataIndex==y&&(counter_Array[y]=counter_Index++);break}}}));e=split_into_chunks(c,200)[0];for(var z in newData)e=e.replace(newData[z],"<span id='data' style='color:black;background-color:orange'>"+newData[z]+" </span>");$("#contents").html(e);0<100*b/counter_total&&41>100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+
(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em></strong>and <strong style="color:green">'+(100-100*b/counter_total).toFixed(2)+"% original. It needs optimal improvement</strong></span><br /><br />"):40<100*b/counter_total&&100>100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em> </strong>and <strong style="color:green">'+(100-100*b/counter_total).toFixed(2)+
'% original. </strong><strong style="color:red">It needs critical improvement</strong></span><br />'):100==100*b/counter_total?$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:orange">'+(100*b/counter_total).toFixed(2)+'% <em>plagiarised</em> </strong>and<strong style="color:red">it needs critical improvement</strong></span><br />'):$("#plagPlagiarised").html('<br /><br /><span><strong>Your document is: </strong><strong style="color:green">100% original</strong></span><br />');
$("#urlSource").show()}})}),$(document).ajaxStop(function(){$("#hideIt").hide()}))};
